'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import Link from 'next/link'
import jsPDF from 'jspdf'
import { Logo } from '../../components/Logo'

const questions = [
  {
    id: 'industry',
    title: 'What industry does your organization operate in?',
    options: ['Financial Services / Banking', 'Healthcare / Life Sciences', 'Government / Defense', 'Technology / SaaS', 'Other']
  },
  {
    id: 'data_lifespan',
    title: 'How long must your most sensitive data remain strictly confidential?',
    options: ['< 5 years', '5-10 years', '10-25 years', '25+ years (e.g. state secrets, genomic data)']
  },
  {
    id: 'crypto_usage',
    title: 'Which cryptographic protocols do you currently use heavily? (Select primary)',
    options: ['RSA (Signatures or Key Exchange)', 'ECDSA / ECDH (Elliptic Curve)', 'AES-256 (Symmetric)', 'I am not sure']
  },
  {
    id: 'timeline',
    title: 'When is your organization planning to begin migrating to NIST PQC standards?',
    options: ['Already started', 'Within 1-2 years', 'Within 3-5 years', 'No current plans']
  }
]

export default function AssessmentPage() {
  const [currentStep, setCurrentStep] = useState(0)
  const [answers, setAnswers] = useState<Record<string, string>>({})
  const [isGenerating, setIsGenerating] = useState(false)

  const handleSelect = (option: string) => {
    setAnswers(prev => ({ ...prev, [questions[currentStep].id]: option }))
    
    setTimeout(() => {
      if (currentStep < questions.length) {
        setCurrentStep(prev => prev + 1)
      }
    }, 300)
  }

  const generatePDF = () => {
    setIsGenerating(true)
    setTimeout(() => {
      const doc = new jsPDF()
      
      doc.setFontSize(22)
      doc.setTextColor(26, 27, 37) // ink
      doc.text('Post-Quantum Strategy Brief', 20, 30)
      
      doc.setFontSize(12)
      doc.setTextColor(156, 163, 175) // graphite
      doc.text('Generated by Spectra Pulse', 20, 40)
      
      doc.setDrawColor(229, 229, 224) // border
      doc.line(20, 45, 190, 45)

      doc.setFontSize(16)
      doc.setTextColor(26, 27, 37)
      doc.text('1. Risk Profile Assessment', 20, 60)

      doc.setFontSize(11)
      doc.text(\`Industry: \${answers.industry || 'Unknown'}\`, 25, 70)
      doc.text(\`Data Secrecy Lifespan: \${answers.data_lifespan || 'Unknown'}\`, 25, 80)
      doc.text(\`Primary Cryptography: \${answers.crypto_usage || 'Unknown'}\`, 25, 90)
      doc.text(\`Migration Timeline: \${answers.timeline || 'Unknown'}\`, 25, 100)

      doc.setFontSize(16)
      doc.text("2. Mosca's Theorem Analysis", 20, 120)
      
      let lifespanYears = 10
      if (answers.data_lifespan?.includes('25+')) lifespanYears = 25
      else if (answers.data_lifespan?.includes('10-25')) lifespanYears = 15
      
      let migrationYears = 3
      if (answers.timeline?.includes('1-2')) migrationYears = 2
      else if (answers.timeline?.includes('No current')) migrationYears = 7

      const qDayEstimate = 7 
      const totalRiskYears = lifespanYears + migrationYears

      doc.setFontSize(11)
      doc.text(\`Migration Time (y) + Data Shelf-life (x) = \${totalRiskYears} years\`, 25, 130)
      doc.text(\`Estimated Time to Q-Day (z) = \${qDayEstimate} years\`, 25, 140)

      if (totalRiskYears > qDayEstimate) {
        doc.setTextColor(239, 68, 68) // critical
        doc.text('CONCLUSION: CRITICAL RISK. x + y > z.', 25, 155)
        doc.text('Your data will be vulnerable to Harvest-Now-Decrypt-Later (HNDL) attacks', 25, 165)
        doc.text('before you finish migrating. Immediate action required.', 25, 175)
      } else {
        doc.setTextColor(22, 163, 74) // safe
        doc.text('CONCLUSION: MODERATE RISK. x + y <= z.', 25, 155)
        doc.text('You have sufficient time to migrate, provided execution begins on schedule.', 25, 165)
      }

      doc.setTextColor(26, 27, 37)
      doc.setFontSize(16)
      doc.text('3. Recommended Action Plan', 20, 195)
      
      doc.setFontSize(11)
      doc.text('1. Run spectra scan across your entire CI/CD pipeline to generate a CBOM.', 25, 205)
      doc.text('2. Identify and isolate all asymmetric encryption (RSA/ECC) endpoints.', 25, 215)
      doc.text('3. Transition TLS connections to ML-KEM hybrid key exchanges.', 25, 225)

      doc.save('spectra-pqc-strategy-brief.pdf')
      setIsGenerating(false)
    }, 1500)
  }

  return (
    <div className="min-h-screen bg-void text-surface font-sans flex flex-col">
      <header className="border-b border-border-dark px-8 h-16 flex items-center justify-between shrink-0">
        <Link href="/" className="flex items-center gap-2">
          <Logo />
          <span className="text-graphite font-mono text-[14px] ml-4">/ assessment</span>
        </Link>
        <div className="font-mono text-[14px] text-graphite uppercase tracking-widest tabular-nums">
          Step {Math.min(currentStep + 1, questions.length)} of {questions.length}
        </div>
      </header>

      <main className="flex-1 flex items-center justify-center p-8">
        <div className="w-full max-w-[800px]">
          <AnimatePresence mode="wait">
            {currentStep < questions.length ? (
              <motion.div
                key={currentStep}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.3 }}
                className="w-full"
              >
                <div className="font-mono text-[12px] text-graphite uppercase tracking-widest mb-6">Question {currentStep + 1}</div>
                <h1 className="font-serif text-[39px] font-light text-surface mb-12 leading-tight">
                  {questions[currentStep].title}
                </h1>
                <div className="space-y-4">
                  {questions[currentStep].options.map((opt, i) => (
                    <button
                      key={i}
                      onClick={() => handleSelect(opt)}
                      className={\`w-full text-left px-8 py-5 border transition-colors font-sans text-[16px] group
                        \${answers[questions[currentStep].id] === opt 
                          ? 'border-calibration bg-calibration/10 text-surface' 
                          : 'border-border-dark bg-obsidian text-graphite hover:border-graphite'}\`}
                    >
                      {opt}
                    </button>
                  ))}
                </div>

                {currentStep > 0 && (
                  <button 
                    onClick={() => setCurrentStep(prev => prev - 1)}
                    className="mt-12 font-sans text-[14px] text-graphite hover:text-surface transition-colors"
                  >
                    ← Back
                  </button>
                )}
              </motion.div>
            ) : (
              <motion.div
                key="completion"
                initial={{ opacity: 0, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                className="text-center bg-obsidian border border-border-dark p-16"
              >
                <div className="font-mono text-[61px] text-surface mb-8 opacity-60">✓</div>
                <h2 className="font-serif text-[39px] font-light text-surface mb-4">Assessment Complete</h2>
                <p className="font-sans text-[14px] text-graphite mb-12 max-w-md mx-auto leading-relaxed">
                  We've analyzed your cryptographic footprint against Mosca's Theorem. Your custom PQC strategy brief is ready.
                </p>
                <button
                  onClick={generatePDF}
                  disabled={isGenerating}
                  className="px-8 py-4 bg-calibration hover:bg-calibration-light disabled:opacity-50 text-surface font-sans text-[14px] font-medium transition-colors"
                >
                  {isGenerating ? 'Generating PDF...' : 'Download Strategy Brief →'}
                </button>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </main>
    </div>
  )
}
