'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Shield, ArrowRight, ArrowLeft, CheckCircle, FileText } from 'lucide-react'
import Link from 'next/link'
import jsPDF from 'jspdf'

const questions = [
  {
    id: 'industry',
    title: 'What industry does your organization operate in?',
    options: ['Financial Services / Banking', 'Healthcare / Life Sciences', 'Government / Defense', 'Technology / SaaS', 'Other']
  },
  {
    id: 'data_lifespan',
    title: 'How long must your most sensitive data remain strictly confidential?',
    options: ['< 5 years', '5-10 years', '10-25 years', '25+ years (e.g. state secrets, genomic data)']
  },
  {
    id: 'crypto_usage',
    title: 'Which cryptographic protocols do you currently use heavily? (Select primary)',
    options: ['RSA (Signatures or Key Exchange)', 'ECDSA / ECDH (Elliptic Curve)', 'AES-256 (Symmetric)', 'I am not sure']
  },
  {
    id: 'timeline',
    title: 'When is your organization planning to begin migrating to NIST PQC standards (ML-KEM, ML-DSA)?',
    options: ['Already started', 'Within 1-2 years', 'Within 3-5 years', 'No current plans']
  }
]

export default function AssessmentPage() {
  const [currentStep, setCurrentStep] = useState(0)
  const [answers, setAnswers] = useState<Record<string, string>>({})
  const [isGenerating, setIsGenerating] = useState(false)

  const handleSelect = (option: string) => {
    setAnswers(prev => ({ ...prev, [questions[currentStep].id]: option }))
    
    // Auto advance after short delay
    setTimeout(() => {
      if (currentStep < questions.length) {
        setCurrentStep(prev => prev + 1)
      }
    }, 400)
  }

  const generatePDF = () => {
    setIsGenerating(true)
    setTimeout(() => {
      const doc = new jsPDF()
      
      // Header
      doc.setFontSize(22)
      doc.setTextColor(30, 58, 138) // dark blue
      doc.text('Post-Quantum Strategy Brief', 20, 30)
      
      doc.setFontSize(12)
      doc.setTextColor(100)
      doc.text('Generated by Spectra - The Quantum Risk Engine', 20, 40)
      
      // Line
      doc.setDrawColor(200)
      doc.line(20, 45, 190, 45)

      // Assessment Profile
      doc.setFontSize(16)
      doc.setTextColor(0)
      doc.text('1. Risk Profile Assessment', 20, 60)

      doc.setFontSize(11)
      doc.text(`Industry: ${answers.industry || 'Unknown'}`, 25, 70)
      doc.text(`Data Secrecy Lifespan: ${answers.data_lifespan || 'Unknown'}`, 25, 80)
      doc.text(`Primary Cryptography: ${answers.crypto_usage || 'Unknown'}`, 25, 90)
      doc.text(`Migration Timeline: ${answers.timeline || 'Unknown'}`, 25, 100)

      // Mosca's Theorem Analysis
      doc.setFontSize(16)
      doc.text("2. Mosca's Theorem Analysis", 20, 120)
      
      let lifespanYears = 10
      if (answers.data_lifespan?.includes('25+')) lifespanYears = 25
      else if (answers.data_lifespan?.includes('10-25')) lifespanYears = 15
      
      let migrationYears = 3
      if (answers.timeline?.includes('1-2')) migrationYears = 2
      else if (answers.timeline?.includes('No current')) migrationYears = 7

      const qDayEstimate = 7 // Optimistic estimate for CRQC in years
      const totalRiskYears = lifespanYears + migrationYears

      doc.setFontSize(11)
      doc.text(`Migration Time (y) + Data Shelf-life (x) = ${totalRiskYears} years`, 25, 130)
      doc.text(`Estimated Time to Q-Day (z) = ${qDayEstimate} years`, 25, 140)

      if (totalRiskYears > qDayEstimate) {
        doc.setTextColor(220, 38, 38)
        doc.text('CONCLUSION: CRITICAL RISK. x + y > z.', 25, 155)
        doc.text('Your data will be vulnerable to Harvest-Now-Decrypt-Later (HNDL) attacks', 25, 165)
        doc.text('before you finish migrating. Immediate action required.', 25, 175)
      } else {
        doc.setTextColor(22, 163, 74)
        doc.text('CONCLUSION: MODERATE RISK. x + y <= z.', 25, 155)
        doc.text('You have sufficient time to migrate, provided execution begins on schedule.', 25, 165)
      }

      // Action Items
      doc.setTextColor(0)
      doc.setFontSize(16)
      doc.text('3. Recommended Action Plan', 20, 195)
      
      doc.setFontSize(11)
      doc.text('1. Run Spectra across your entire CI/CD pipeline to generate a CBOM.', 25, 205)
      doc.text('2. Identify and isolate all asymmetric encryption (RSA/ECC) endpoints.', 25, 215)
      doc.text('3. Transition TLS connections to ML-KEM hybrid key exchanges.', 25, 225)

      doc.save('spectra-pqc-strategy-brief.pdf')
      setIsGenerating(false)
    }, 1500)
  }

  return (
    <div className="min-h-screen bg-slate-950 text-slate-300 font-sans flex flex-col">
      <header className="px-6 py-6 flex items-center justify-between">
        <Link href="/" className="flex items-center gap-2 font-bold text-white">
          <Shield className="w-5 h-5 text-indigo-400" />
          Spectra Assessment
        </Link>
        <div className="text-sm text-slate-500 font-mono">
          Step {Math.min(currentStep + 1, questions.length)} of {questions.length}
        </div>
      </header>

      <main className="flex-1 flex items-center justify-center p-6">
        <div className="w-full max-w-2xl">
          <AnimatePresence mode="wait">
            {currentStep < questions.length ? (
              <motion.div
                key={currentStep}
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.3 }}
                className="w-full"
              >
                <div className="text-indigo-400 font-mono text-sm mb-4">QUESTION {currentStep + 1}</div>
                <h1 className="text-3xl md:text-4xl font-bold text-white mb-8 leading-tight">
                  {questions[currentStep].title}
                </h1>
                <div className="space-y-3">
                  {questions[currentStep].options.map((opt, i) => (
                    <button
                      key={i}
                      onClick={() => handleSelect(opt)}
                      className={`w-full text-left px-6 py-4 rounded-xl border-2 transition-all duration-200 flex items-center justify-between group
                        ${answers[questions[currentStep].id] === opt 
                          ? 'border-indigo-500 bg-indigo-500/10 text-white' 
                          : 'border-slate-800 bg-slate-900/50 text-slate-300 hover:border-slate-600 hover:bg-slate-800'}`}
                    >
                      <span className="text-lg font-medium">{opt}</span>
                      <div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center
                        ${answers[questions[currentStep].id] === opt ? 'border-indigo-500 bg-indigo-500' : 'border-slate-600 group-hover:border-slate-400'}`}>
                        {answers[questions[currentStep].id] === opt && <div className="w-2 h-2 rounded-full bg-white" />}
                      </div>
                    </button>
                  ))}
                </div>

                <div className="mt-8 flex items-center gap-4">
                  {currentStep > 0 && (
                    <button 
                      onClick={() => setCurrentStep(prev => prev - 1)}
                      className="px-4 py-2 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 flex items-center gap-2 transition-colors"
                    >
                      <ArrowLeft className="w-4 h-4" /> Back
                    </button>
                  )}
                </div>
              </motion.div>
            ) : (
              <motion.div
                key="completion"
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                className="text-center bg-slate-900 border border-slate-800 p-12 rounded-3xl"
              >
                <div className="w-20 h-20 bg-emerald-500/20 text-emerald-400 rounded-full flex items-center justify-center mx-auto mb-6">
                  <CheckCircle className="w-10 h-10" />
                </div>
                <h2 className="text-3xl font-bold text-white mb-4">Assessment Complete</h2>
                <p className="text-slate-400 mb-8 max-w-md mx-auto text-lg">
                  We've analyzed your cryptographic footprint against Mosca's Theorem. Your custom PQC strategy brief is ready.
                </p>
                <button
                  onClick={generatePDF}
                  disabled={isGenerating}
                  className="px-8 py-4 rounded-xl bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-600/50 text-white font-bold text-lg inline-flex items-center gap-3 transition-all"
                >
                  <FileText className="w-5 h-5" />
                  {isGenerating ? 'Generating PDF...' : 'Download Strategy Brief'}
                </button>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </main>
    </div>
  )
}
